function img() {
  a1.style.borderRight = "5px solid blue"
  a2.style.borderRight = "0"
  a3.style.borderRight = "0"
  a4.style.borderRight = "0"
  a1.style.color = "blue"
  a2.style.color = "#fff"
  a3.style.color = "#fff"
  a4.style.color = "#fff"
  img1.src = "image/img (1).jpg"
  img2.src = "image/img (2).jpg"
  img3.src = "image/img (3).jpg"
  img4.src = "image/img (4).jpg"
  img5.src = "image/img (5).jpg"
  img6.src = "image/img (6).jpg"
  img7.src = "image/img (7).jpg"
  img8.src = "image/img (8).jpg"
  img9.src = "image/img (9).jpg"
  img10.src = "image/img (10).png"
}
function gameImg() {
  a2.style.borderRight = "5px solid blue"
  a1.style.borderRight = "0"
  a3.style.borderRight = "0"
  a4.style.borderRight = "0"
  a2.style.color = "blue"
  a1.style.color = "#fff"
  a3.style.color = "#fff"
  a4.style.color = "#fff"
  img1.src = "image/game-img5 (1).jpg"
  img2.src = "image/game-img5 (2).png"
  img3.src = "image/game-img5 (3).jpg"
  img4.src = "image/game-img5 (4).jpg"
  img5.src = "image/game-img5 (5).jpg"
  img6.src = "image/game-img5 (6).jpg"
  img7.src = "image/game-img5 (7).jpg"
  img8.src = "image/game-img5 (8).jpg"
  img9.src = "image/game-img5 (9).png"
  img10.src = "image/game-img5 (10).jpg"
}
function animation() {
  a3.style.borderRight = "5px solid blue"
  a2.style.borderRight = "0"
  a1.style.borderRight = "0"
  a4.style.borderRight = "0"
  a3.style.color = "blue"
  a2.style.color = "#fff"
  a1.style.color = "#fff"
  a4.style.color = "#fff"
  img1.src = "image/animation (1).jpg"
  img2.src = "image/animation (2).png"
  img3.src = "image/animation (3).jpg"
  img4.src = "image/animation (4).jpg"
  img5.src = "image/animation (5).jpg"
  img6.src = "image/animation (6).jpg"
  img7.src = "image/animation (7).jpg"
  img8.src = "image/animation (8).jpg"
  img9.src = "image/animation (9).jpg"
  img10.src = "image/animation (10).png"
}
function img1() {
  a4.style.borderRight = "5px solid blue"
  a2.style.borderRight = "0"
  a3.style.borderRight = "0"
  a1.style.borderRight = "0"
  a4.style.color = "blue"
  a2.style.color = "#fff"
  a3.style.color = "#fff"
  a1.style.color = "#fff"
  img1.src = "image/img1 (1).jpg"
  img2.src = "image/img1 (2).jpg"
  img3.src = "image/img1 (3).jpg"
  img4.src = "image/img1 (4).jpg"
  img5.src = "image/img1 (5).jpg"
  img6.src = "image/img1 (6).jpg"
  img7.src = "image/img1 (7).png"
  img8.src = "image/img1 (8).jpg"
  img9.src = "image/img1 (9).jpg"
  img10.src = "image/img1 (10).png"
}